# client/Cargo.toml
[package]
name = "soltrack-client"
version = "0.1.0"

[dependencies]
anchor-client = "0.29.0"
solana-client = "1.17.0"
solana-sdk = "1.17.0"
sodiumoxide = "0.2.7"
tokio = { version = "1.0", features = ["full"] }